export default {
  FETCH_USER_PENDING: Symbol("FETCH_USER_PENDING"),
  FETCH_USER_SUCCESS: Symbol("FETCH_USER_SUCCESS"),
  FETCH_USER_FAILURE: Symbol("FETCH_USER_FAILURE"),

  CHECK_EMAIL_PENDING: Symbol("CHECK_EMAIL_PENDING"),
  CHECK_EMAIL_SUCCESS: Symbol("CHECK_EMAIL_SUCCESS"),
  CHECK_EMAIL_FAILURE: Symbol("CHECK_EMAIL_FAILURE"),

  LOGIN_PENDING: Symbol("LOGIN_PENDING"),
  LOGIN_SUCCESS: Symbol("LOGIN_SUCCESS"),
  LOGIN_FAILURE: Symbol("LOGIN_FAILURE"),

  SIGNUP_FIELD_ERROR: Symbol("SIGNUP_FIELD_ERROR"),
  SIGNUP_FIELD_OK: Symbol("SIGNUP_FIELD_OK"),

  SIGNUP_CHECK_ASYNC_PENDING: Symbol("SIGNUP_CHECK_ASYNC_PENDING"),
  SIGNUP_CHECK_ASYNC_SUCCESS: Symbol("SIGNUP_CHECK_ASYNC_SUCCESS"),
  SIGNUP_CHECK_ASYNC_FAILURE: Symbol("SIGNUP_CHECK_ASYNC_FAILURE"),

  SIGNUP_PENDING: Symbol("SIGNUP_PENDING"),
  SIGNUP_SUCCESS: Symbol("SIGNUP_SUCCESS"),
  SIGNUP_FAILURE: Symbol("SIGNUP_FAILURE"),

  LOGOUT: Symbol("LOGOUT")

};
