export default {
  FETCH_USER_PENDING: Symbol("FETCH_USER_PENDING"),
  FETCH_USER_SUCCESS: Symbol("FETCH_USER_SUCCESS"),
  FETCH_USER_FAILURE: Symbol("FETCH_USER_FAILURE"),

  LOGIN_PENDING: Symbol("LOGIN_PENDING"),
  LOGIN_SUCCESS: Symbol("LOGIN_SUCCESS"),
  LOGIN_FAILURE: Symbol("LOGIN_FAILURE"),

  SIGNUP_PENDING: Symbol("SIGNUP_PENDING"),
  SIGNUP_SUCCESS: Symbol("SIGNUP_SUCCESS"),
  SIGNUP_FAILURE: Symbol("SIGNUP_FAILURE"),

  LOGOUT: Symbol("LOGOUT")

};
