export default {
  CHANGE_PASSWORD_RESET:  Symbol("CHANGE_PASSWORD_RESET"),
  CHANGE_PASSWORD_FORM_INVALID:  Symbol("CHANGE_PASSWORD_FORM_INVALID"),
  CHANGE_PASSWORD_PENDING:  Symbol("CHANGE_PASSWORD_PENDING"),
  CHANGE_PASSWORD_SUCCESS:  Symbol("CHANGE_PASSWORD_SUCCESS"),
  CHANGE_PASSWORD_FAILURE:  Symbol("CHANGE_PASSWORD_FAILURE")
};
