export default {

  FETCH_PHOTO_DETAIL_PENDING: "FETCH_PHOTO_DETAIL_PENDING",
  FETCH_PHOTO_DETAIL_SUCCESS: "FETCH_PHOTO_DETAIL_SUCCESS",
  FETCH_PHOTO_DETAIL_FAILURE: "FETCH_PHOTO_DETAIL_FAILURE",

  TOGGLE_PHOTO_TITLE_EDIT: "TOGGLE_PHOTO_TITLE_EDIT",
  TOGGLE_PHOTO_TAGS_EDIT: "TOGGLE_PHOTO_TAGS_EDIT",

  UPDATE_PHOTO_TAGS_PENDING: "UPDATE_PHOTO_TAGS_PENDING",
  UPDATE_PHOTO_TAGS_SUCCESS: "UPDATE_PHOTO_TAGS_SUCCESS",
  UPDATE_PHOTO_TAGS_FAILURE: "UPDATE_PHOTO_TAGS_FAILURE",

  UPDATE_PHOTO_TITLE_PENDING: "UPDATE_PHOTO_TITLE_PENDING",
  UPDATE_PHOTO_TITLE_SUCCESS: "UPDATE_PHOTO_TITLE_SUCCESS",
  UPDATE_PHOTO_TITLE_FAILURE: "UPDATE_PHOTO_TITLE_FAILURE",

  VOTE_UP_PHOTO_PENDING: "VOTE_UP_PHOTO_PENDING",
  VOTE_UP_PHOTO_SUCCESS: "VOTE_UP_PHOTO_SUCCESS",
  VOTE_UP_PHOTO_FAILURE: "VOTE_UP_PHOTO_FAILURE",

  VOTE_DOWN_PHOTO_PENDING: "VOTE_DOWN_PHOTO_PENDING",
  VOTE_DOWN_PHOTO_SUCCESS: "VOTE_DOWN_PHOTO_SUCCESS",
  VOTE_DOWN_PHOTO_FAILURE: "VOTE_DOWN_PHOTO_FAILURE",

  DELETE_PHOTO_PENDING: "DELETE_PHOTO_PENDING",
  DELETE_PHOTO_SUCCESS: "DELETE_PHOTO_SUCCESS",
  DELETE_PHOTO_FAILURE: "DELETE_PHOTO_FAILURE"

};
