export default {
  RECOVER_PASSWORD_RESET: "RECOVER_PASSWORD_RESET",
  RECOVER_PASSWORD_PENDING: "RECOVER_PASSWORD_PENDING",
  RECOVER_PASSWORD_SUCCESS: "RECOVER_PASSWORD_SUCCESS",
  RECOVER_PASSWORD_FAILURE: "RECOVER_PASSWORD_FAILURE"
};
