export default {
  RECOVER_PASSWORD_RESET: Symbol("RECOVER_PASSWORD_RESET"),
  RECOVER_PASSWORD_PENDING: Symbol("RECOVER_PASSWORD_PENDING"),
  RECOVER_PASSWORD_SUCCESS: Symbol("RECOVER_PASSWORD_SUCCESS"),
  RECOVER_PASSWORD_FAILURE: Symbol("RECOVER_PASSWORD_FAILURE")
};
