export default {

  FETCH_TAGS_PENDING: Symbol("FETCH_TAGS_PENDING"),
  FETCH_TAGS_SUCCESS: Symbol("FETCH_TAGS_SUCCESS"),
  FETCH_TAGS_FAILURE: Symbol("FETCH_TAGS_FAILURE"),

  FILTER_TAGS: Symbol("FILTER_TAGS"),
  ORDER_TAGS: Symbol("ORDER_TAGS")
};
