export default {

  FETCH_TAGS_PENDING: "FETCH_TAGS_PENDING",
  FETCH_TAGS_SUCCESS: "FETCH_TAGS_SUCCESS",
  FETCH_TAGS_FAILURE: "FETCH_TAGS_FAILURE",

  FILTER_TAGS: "FILTER_TAGS",
  ORDER_TAGS: "ORDER_TAGS"
};
