export default {

  PHOTO_PREVIEW: Symbol("PHOTO_PREVIEW"),

  UPLOAD_RESET: Symbol("UPLOAD_RESET"),
  UPLOAD_FORM_INVALID: Symbol("UPLOAD_FORM_ERRORS"),
  UPLOAD_PENDING: Symbol("UPLOAD_PENDING"),
  UPLOAD_SUCCESS: Symbol("UPLOAD_SUCCESS"),
  UPLOAD_FAILURE: Symbol("UPLOAD_FAILURE")

};
