export default {

  PHOTO_PREVIEW: "PHOTO_PREVIEW",

  UPLOAD_RESET: "UPLOAD_RESET",
  UPLOAD_FORM_INVALID: "UPLOAD_FORM_ERRORS",
  UPLOAD_PENDING: "UPLOAD_PENDING",
  UPLOAD_SUCCESS: "UPLOAD_SUCCESS",
  UPLOAD_FAILURE: "UPLOAD_FAILURE"

};
