/* jslint ignore:start */
export const ActionTypes = {
  FETCH_PHOTOS_PENDING: "FETCH_PHOTOS_PENDING",
  FETCH_PHOTOS_SUCCESS: "FETCH_PHOTOS_SUCCESS",
  FETCH_PHOTOS_FAILURE: "FETCH_PHOTOS_FAILURE",

  FETCH_PHOTO_DETAIL_PENDING: "FETCH_PHOTO_DETAIL_PENDING",
  FETCH_PHOTO_DETAIL_SUCCESS: "FETCH_PHOTO_DETAIL_SUCCESS",
  FETCH_PHOTO_DETAIL_FAILURE: "FETCH_PHOTO_DETAIL_FAILURE",

  TOGGLE_PHOTO_TITLE_EDIT: "TOGGLE_PHOTO_TITLE_EDIT",
  TOGGLE_PHOTO_TAGS_EDIT: "TOGGLE_PHOTO_TAGS_EDIT",

  UPDATE_PHOTO_TAGS_PENDING: "UPDATE_PHOTO_TAGS_PENDING",
  UPDATE_PHOTO_TAGS_SUCCESS: "UPDATE_PHOTO_TAGS_SUCCESS",
  UPDATE_PHOTO_TAGS_FAILURE: "UPDATE_PHOTO_TAGS_FAILURE",

  UPDATE_PHOTO_TITLE_PENDING: "UPDATE_PHOTO_TITLE_PENDING",
  UPDATE_PHOTO_TITLE_SUCCESS: "UPDATE_PHOTO_TITLE_SUCCESS",
  UPDATE_PHOTO_TITLE_FAILURE: "UPDATE_PHOTO_TITLE_FAILURE",

  DELETE_PHOTO_PENDING: "DELETE_PHOTO_PENDING",
  DELETE_PHOTO_SUCCESS: "DELETE_PHOTO_SUCCESS",
  DELETE_PHOTO_FAILURE: "DELETE_PHOTO_FAILURE",

  FETCH_USER_PENDING: "FETCH_USER_PENDING",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_FAILURE: "FETCH_USER_FAILURE",

  LOGIN_PENDING: "LOGIN_PENDING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT: "LOGOUT",

  DELETE_MESSAGE: "DELETE_MESSAGE",

  PHOTO_PREVIEW: "PHOTO_PREVIEW",

  UPLOAD_PENDING: "UPLOAD_PENDING",
  UPLOAD_SUCCESS: "UPLOAD_SUCCESS",
  UPLOAD_FAILURE: "UPLOAD_FAILURE",

  FETCH_TAGS_PENDING: "FETCH_TAGS_PENDING",
  FETCH_TAGS_SUCCESS: "FETCH_TAGS_SUCCESS",
  FETCH_TAGS_FAILURE: "FETCH_TAGS_FAILURE",
  FILTER_TAGS: "FILTER_TAGS",
  ORDER_TAGS: "ORDER_TAGS"
}
