/* jslint ignore:start */
export const ActionTypes = {
  GET_PHOTOS: "GET_PHOTOS",
  GET_PHOTO_DETAIL: "GET_PHOTO_DETAIL",
  GET_USER: "GET_USER",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  NEW_MESSAGE: "NEW_MESSAGE",
  DELETE_MESSAGE: "DELETE_MESSAGE",
  PHOTO_PREVIEW: "PHOTO_PREVIEW",
  PHOTO_UPLOAD: "PHOTO_UPLOAD",
  UPLOAD_RESET: "UPLOAD_RESET",
  UPLOAD_ERRORS: "UPLOAD_ERRORS",
  UPLOAD_SUBMITTED: "UPLOAD_SUBMITTED"
}
